language: ruby
rvm:
  - 2.2
  - jruby
  
before_install:
  - gem update --system
  - gem install bundler

env:
  global:
    - LT_USERNAME=${LAMBDATEST_USERNAME}
    - LT_ACCESS_KEY=${LAMBDATEST_KEY}
    
script:
  - bundle install
  - bundle exec rake single 
